package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	gigachad "github.com/sahidrahman404/gigachad-api"
	"github.com/sahidrahman404/gigachad-api/ent"
	"github.com/sahidrahman404/gigachad-api/internal/img"
	"github.com/sahidrahman404/gigachad-api/internal/purifier"
)

// CreateExercise is the resolver for the createExercise field.
func (r *mutationResolver) CreateExercise(ctx context.Context, input gigachad.CreateExerciseInput) (*ent.Exercise, error) {
	uCtx := r.getUserFromCtx(ctx)

	ex, err := r.client.Exercise.Create().
		SetName(input.Name).
		SetImage(img.SetNillableImageField(input.Image, *r.awsCfg, r.imgproxy)).
		SetNillableHowTo(purifier.PurifyHTML(input.HowTo, r.purifier)).
		SetNillableUserID(uCtx.GetUserID()).
		AddMusclesGroupIDs(input.MusclesGroupIDs...).
		AddExerciseTypeIDs(input.ExerciseTypeIDs...).
		Save(ctx)
	if err != nil {
		return nil, r.defaultError(err)
	}
	return ex, nil
}

// UpdateExercise is the resolver for the updateExercise field.
func (r *mutationResolver) UpdateExercise(ctx context.Context, input gigachad.UpdateExerciseInput) (*ent.Exercise, error) {
	userCtx := r.getUserFromCtx(ctx)

	switch input.Image {
	case nil:
		err := r.client.Exercise.Create().
			SetID(input.ID).
			SetName(input.Name).
			SetNillableHowTo(purifier.PurifyHTML(input.HowTo, r.purifier)).
			SetNillableUserID(userCtx.GetUserID()).
			AddMusclesGroupIDs(input.MusclesGroupIDs...).
			AddExerciseTypeIDs(input.ExerciseTypeIDs...).
			OnConflict().
			UpdateNewValues().
			Exec(ctx)
		if err != nil {
			return nil, r.defaultError(err)
		}
	default:
		err := r.client.Exercise.Create().
			SetID(input.ID).
			SetName(input.Name).
			SetImage(img.SetNillableImageField(input.Image, *r.awsCfg, r.imgproxy)).
			SetNillableHowTo(purifier.PurifyHTML(input.HowTo, r.purifier)).
			SetNillableUserID(userCtx.GetUserID()).
			AddMusclesGroupIDs(input.MusclesGroupIDs...).
			AddExerciseTypeIDs(input.ExerciseTypeIDs...).
			OnConflict().
			UpdateNewValues().
			Exec(ctx)
		if err != nil {
			return nil, r.defaultError(err)
		}
	}

	exercise, err := r.client.Exercise.Get(ctx, input.ID)
	if err != nil {
		return nil, r.defaultError(err)
	}
	return exercise, nil
}

// DeleteExercise is the resolver for the deleteExercise field.
func (r *mutationResolver) DeleteExercise(ctx context.Context, input gigachad.DeleteExerciseInput) (*ent.Exercise, error) {
	err := r.client.Exercise.DeleteOneID(input.ID).Exec(ctx)
	if err != nil {
		return nil, r.defaultError(err)
	}

	return &ent.Exercise{ID: input.ID}, nil
}
