package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	gigachad "github.com/sahidrahman404/gigachad-api"
	"github.com/sahidrahman404/gigachad-api/ent"
)

// CreateRoutineExercise is the resolver for the CreateRoutineExercise field.
func (r *mutationResolver) CreateRoutineExercise(ctx context.Context, input gigachad.CreateRoutineExerciseInput) (*ent.RoutineExercise, error) {
	panic(fmt.Errorf("not implemented: CreateRoutineExercise - CreateRoutineExercise"))
}
