// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sahidrahman404/gigachad-api/ent/predicate"
	"github.com/sahidrahman404/gigachad-api/ent/routineexercise"
)

// RoutineExerciseDelete is the builder for deleting a RoutineExercise entity.
type RoutineExerciseDelete struct {
	config
	hooks    []Hook
	mutation *RoutineExerciseMutation
}

// Where appends a list predicates to the RoutineExerciseDelete builder.
func (red *RoutineExerciseDelete) Where(ps ...predicate.RoutineExercise) *RoutineExerciseDelete {
	red.mutation.Where(ps...)
	return red
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (red *RoutineExerciseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, red.sqlExec, red.mutation, red.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (red *RoutineExerciseDelete) ExecX(ctx context.Context) int {
	n, err := red.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (red *RoutineExerciseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(routineexercise.Table, sqlgraph.NewFieldSpec(routineexercise.FieldID, field.TypeString))
	if ps := red.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, red.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	red.mutation.done = true
	return affected, err
}

// RoutineExerciseDeleteOne is the builder for deleting a single RoutineExercise entity.
type RoutineExerciseDeleteOne struct {
	red *RoutineExerciseDelete
}

// Where appends a list predicates to the RoutineExerciseDelete builder.
func (redo *RoutineExerciseDeleteOne) Where(ps ...predicate.RoutineExercise) *RoutineExerciseDeleteOne {
	redo.red.mutation.Where(ps...)
	return redo
}

// Exec executes the deletion query.
func (redo *RoutineExerciseDeleteOne) Exec(ctx context.Context) error {
	n, err := redo.red.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{routineexercise.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (redo *RoutineExerciseDeleteOne) ExecX(ctx context.Context) {
	if err := redo.Exec(ctx); err != nil {
		panic(err)
	}
}
