// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sahidrahman404/gigachad-api/ent/exercise"
	"github.com/sahidrahman404/gigachad-api/ent/predicate"
	"github.com/sahidrahman404/gigachad-api/ent/schema/pksuid"
	"github.com/sahidrahman404/gigachad-api/ent/schema/schematype"
	"github.com/sahidrahman404/gigachad-api/ent/user"
	"github.com/sahidrahman404/gigachad-api/ent/workout"
	"github.com/sahidrahman404/gigachad-api/ent/workoutlog"
)

// WorkoutUpdate is the builder for updating Workout entities.
type WorkoutUpdate struct {
	config
	hooks    []Hook
	mutation *WorkoutMutation
}

// Where appends a list predicates to the WorkoutUpdate builder.
func (wu *WorkoutUpdate) Where(ps ...predicate.Workout) *WorkoutUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetVolume sets the "volume" field.
func (wu *WorkoutUpdate) SetVolume(i int) *WorkoutUpdate {
	wu.mutation.ResetVolume()
	wu.mutation.SetVolume(i)
	return wu
}

// SetNillableVolume sets the "volume" field if the given value is not nil.
func (wu *WorkoutUpdate) SetNillableVolume(i *int) *WorkoutUpdate {
	if i != nil {
		wu.SetVolume(*i)
	}
	return wu
}

// AddVolume adds i to the "volume" field.
func (wu *WorkoutUpdate) AddVolume(i int) *WorkoutUpdate {
	wu.mutation.AddVolume(i)
	return wu
}

// SetDuration sets the "duration" field.
func (wu *WorkoutUpdate) SetDuration(s string) *WorkoutUpdate {
	wu.mutation.SetDuration(s)
	return wu
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (wu *WorkoutUpdate) SetNillableDuration(s *string) *WorkoutUpdate {
	if s != nil {
		wu.SetDuration(*s)
	}
	return wu
}

// SetSets sets the "sets" field.
func (wu *WorkoutUpdate) SetSets(i int) *WorkoutUpdate {
	wu.mutation.ResetSets()
	wu.mutation.SetSets(i)
	return wu
}

// SetNillableSets sets the "sets" field if the given value is not nil.
func (wu *WorkoutUpdate) SetNillableSets(i *int) *WorkoutUpdate {
	if i != nil {
		wu.SetSets(*i)
	}
	return wu
}

// AddSets adds i to the "sets" field.
func (wu *WorkoutUpdate) AddSets(i int) *WorkoutUpdate {
	wu.mutation.AddSets(i)
	return wu
}

// SetCreatedAt sets the "created_at" field.
func (wu *WorkoutUpdate) SetCreatedAt(t time.Time) *WorkoutUpdate {
	wu.mutation.SetCreatedAt(t)
	return wu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wu *WorkoutUpdate) SetNillableCreatedAt(t *time.Time) *WorkoutUpdate {
	if t != nil {
		wu.SetCreatedAt(*t)
	}
	return wu
}

// SetImage sets the "image" field.
func (wu *WorkoutUpdate) SetImage(s *schematype.Image) *WorkoutUpdate {
	wu.mutation.SetImage(s)
	return wu
}

// ClearImage clears the value of the "image" field.
func (wu *WorkoutUpdate) ClearImage() *WorkoutUpdate {
	wu.mutation.ClearImage()
	return wu
}

// SetDescription sets the "description" field.
func (wu *WorkoutUpdate) SetDescription(s string) *WorkoutUpdate {
	wu.mutation.SetDescription(s)
	return wu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wu *WorkoutUpdate) SetNillableDescription(s *string) *WorkoutUpdate {
	if s != nil {
		wu.SetDescription(*s)
	}
	return wu
}

// ClearDescription clears the value of the "description" field.
func (wu *WorkoutUpdate) ClearDescription() *WorkoutUpdate {
	wu.mutation.ClearDescription()
	return wu
}

// SetUserID sets the "user_id" field.
func (wu *WorkoutUpdate) SetUserID(pk pksuid.ID) *WorkoutUpdate {
	wu.mutation.SetUserID(pk)
	return wu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wu *WorkoutUpdate) SetNillableUserID(pk *pksuid.ID) *WorkoutUpdate {
	if pk != nil {
		wu.SetUserID(*pk)
	}
	return wu
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (wu *WorkoutUpdate) SetUsersID(id pksuid.ID) *WorkoutUpdate {
	wu.mutation.SetUsersID(id)
	return wu
}

// SetUsers sets the "users" edge to the User entity.
func (wu *WorkoutUpdate) SetUsers(u *User) *WorkoutUpdate {
	return wu.SetUsersID(u.ID)
}

// AddExerciseIDs adds the "exercises" edge to the Exercise entity by IDs.
func (wu *WorkoutUpdate) AddExerciseIDs(ids ...pksuid.ID) *WorkoutUpdate {
	wu.mutation.AddExerciseIDs(ids...)
	return wu
}

// AddExercises adds the "exercises" edges to the Exercise entity.
func (wu *WorkoutUpdate) AddExercises(e ...*Exercise) *WorkoutUpdate {
	ids := make([]pksuid.ID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return wu.AddExerciseIDs(ids...)
}

// AddWorkoutLogIDs adds the "workout_logs" edge to the WorkoutLog entity by IDs.
func (wu *WorkoutUpdate) AddWorkoutLogIDs(ids ...pksuid.ID) *WorkoutUpdate {
	wu.mutation.AddWorkoutLogIDs(ids...)
	return wu
}

// AddWorkoutLogs adds the "workout_logs" edges to the WorkoutLog entity.
func (wu *WorkoutUpdate) AddWorkoutLogs(w ...*WorkoutLog) *WorkoutUpdate {
	ids := make([]pksuid.ID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.AddWorkoutLogIDs(ids...)
}

// Mutation returns the WorkoutMutation object of the builder.
func (wu *WorkoutUpdate) Mutation() *WorkoutMutation {
	return wu.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (wu *WorkoutUpdate) ClearUsers() *WorkoutUpdate {
	wu.mutation.ClearUsers()
	return wu
}

// ClearExercises clears all "exercises" edges to the Exercise entity.
func (wu *WorkoutUpdate) ClearExercises() *WorkoutUpdate {
	wu.mutation.ClearExercises()
	return wu
}

// RemoveExerciseIDs removes the "exercises" edge to Exercise entities by IDs.
func (wu *WorkoutUpdate) RemoveExerciseIDs(ids ...pksuid.ID) *WorkoutUpdate {
	wu.mutation.RemoveExerciseIDs(ids...)
	return wu
}

// RemoveExercises removes "exercises" edges to Exercise entities.
func (wu *WorkoutUpdate) RemoveExercises(e ...*Exercise) *WorkoutUpdate {
	ids := make([]pksuid.ID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return wu.RemoveExerciseIDs(ids...)
}

// ClearWorkoutLogs clears all "workout_logs" edges to the WorkoutLog entity.
func (wu *WorkoutUpdate) ClearWorkoutLogs() *WorkoutUpdate {
	wu.mutation.ClearWorkoutLogs()
	return wu
}

// RemoveWorkoutLogIDs removes the "workout_logs" edge to WorkoutLog entities by IDs.
func (wu *WorkoutUpdate) RemoveWorkoutLogIDs(ids ...pksuid.ID) *WorkoutUpdate {
	wu.mutation.RemoveWorkoutLogIDs(ids...)
	return wu
}

// RemoveWorkoutLogs removes "workout_logs" edges to WorkoutLog entities.
func (wu *WorkoutUpdate) RemoveWorkoutLogs(w ...*WorkoutLog) *WorkoutUpdate {
	ids := make([]pksuid.ID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.RemoveWorkoutLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WorkoutUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkoutUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkoutUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkoutUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WorkoutUpdate) check() error {
	if _, ok := wu.mutation.UsersID(); wu.mutation.UsersCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Workout.users"`)
	}
	return nil
}

func (wu *WorkoutUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workout.Table, workout.Columns, sqlgraph.NewFieldSpec(workout.FieldID, field.TypeString))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Volume(); ok {
		_spec.SetField(workout.FieldVolume, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedVolume(); ok {
		_spec.AddField(workout.FieldVolume, field.TypeInt, value)
	}
	if value, ok := wu.mutation.Duration(); ok {
		_spec.SetField(workout.FieldDuration, field.TypeString, value)
	}
	if value, ok := wu.mutation.Sets(); ok {
		_spec.SetField(workout.FieldSets, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedSets(); ok {
		_spec.AddField(workout.FieldSets, field.TypeInt, value)
	}
	if value, ok := wu.mutation.CreatedAt(); ok {
		_spec.SetField(workout.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wu.mutation.Image(); ok {
		_spec.SetField(workout.FieldImage, field.TypeJSON, value)
	}
	if wu.mutation.ImageCleared() {
		_spec.ClearField(workout.FieldImage, field.TypeJSON)
	}
	if value, ok := wu.mutation.Description(); ok {
		_spec.SetField(workout.FieldDescription, field.TypeString, value)
	}
	if wu.mutation.DescriptionCleared() {
		_spec.ClearField(workout.FieldDescription, field.TypeString)
	}
	if wu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workout.UsersTable,
			Columns: []string{workout.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workout.UsersTable,
			Columns: []string{workout.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workout.ExercisesTable,
			Columns: workout.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeString),
			},
		}
		createE := &WorkoutLogCreate{config: wu.config, mutation: newWorkoutLogMutation(wu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedExercisesIDs(); len(nodes) > 0 && !wu.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workout.ExercisesTable,
			Columns: workout.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &WorkoutLogCreate{config: wu.config, mutation: newWorkoutLogMutation(wu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.ExercisesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workout.ExercisesTable,
			Columns: workout.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &WorkoutLogCreate{config: wu.config, mutation: newWorkoutLogMutation(wu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.WorkoutLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workout.WorkoutLogsTable,
			Columns: []string{workout.WorkoutLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutlog.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedWorkoutLogsIDs(); len(nodes) > 0 && !wu.mutation.WorkoutLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workout.WorkoutLogsTable,
			Columns: []string{workout.WorkoutLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutlog.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.WorkoutLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workout.WorkoutLogsTable,
			Columns: []string{workout.WorkoutLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutlog.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WorkoutUpdateOne is the builder for updating a single Workout entity.
type WorkoutUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkoutMutation
}

// SetVolume sets the "volume" field.
func (wuo *WorkoutUpdateOne) SetVolume(i int) *WorkoutUpdateOne {
	wuo.mutation.ResetVolume()
	wuo.mutation.SetVolume(i)
	return wuo
}

// SetNillableVolume sets the "volume" field if the given value is not nil.
func (wuo *WorkoutUpdateOne) SetNillableVolume(i *int) *WorkoutUpdateOne {
	if i != nil {
		wuo.SetVolume(*i)
	}
	return wuo
}

// AddVolume adds i to the "volume" field.
func (wuo *WorkoutUpdateOne) AddVolume(i int) *WorkoutUpdateOne {
	wuo.mutation.AddVolume(i)
	return wuo
}

// SetDuration sets the "duration" field.
func (wuo *WorkoutUpdateOne) SetDuration(s string) *WorkoutUpdateOne {
	wuo.mutation.SetDuration(s)
	return wuo
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (wuo *WorkoutUpdateOne) SetNillableDuration(s *string) *WorkoutUpdateOne {
	if s != nil {
		wuo.SetDuration(*s)
	}
	return wuo
}

// SetSets sets the "sets" field.
func (wuo *WorkoutUpdateOne) SetSets(i int) *WorkoutUpdateOne {
	wuo.mutation.ResetSets()
	wuo.mutation.SetSets(i)
	return wuo
}

// SetNillableSets sets the "sets" field if the given value is not nil.
func (wuo *WorkoutUpdateOne) SetNillableSets(i *int) *WorkoutUpdateOne {
	if i != nil {
		wuo.SetSets(*i)
	}
	return wuo
}

// AddSets adds i to the "sets" field.
func (wuo *WorkoutUpdateOne) AddSets(i int) *WorkoutUpdateOne {
	wuo.mutation.AddSets(i)
	return wuo
}

// SetCreatedAt sets the "created_at" field.
func (wuo *WorkoutUpdateOne) SetCreatedAt(t time.Time) *WorkoutUpdateOne {
	wuo.mutation.SetCreatedAt(t)
	return wuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wuo *WorkoutUpdateOne) SetNillableCreatedAt(t *time.Time) *WorkoutUpdateOne {
	if t != nil {
		wuo.SetCreatedAt(*t)
	}
	return wuo
}

// SetImage sets the "image" field.
func (wuo *WorkoutUpdateOne) SetImage(s *schematype.Image) *WorkoutUpdateOne {
	wuo.mutation.SetImage(s)
	return wuo
}

// ClearImage clears the value of the "image" field.
func (wuo *WorkoutUpdateOne) ClearImage() *WorkoutUpdateOne {
	wuo.mutation.ClearImage()
	return wuo
}

// SetDescription sets the "description" field.
func (wuo *WorkoutUpdateOne) SetDescription(s string) *WorkoutUpdateOne {
	wuo.mutation.SetDescription(s)
	return wuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wuo *WorkoutUpdateOne) SetNillableDescription(s *string) *WorkoutUpdateOne {
	if s != nil {
		wuo.SetDescription(*s)
	}
	return wuo
}

// ClearDescription clears the value of the "description" field.
func (wuo *WorkoutUpdateOne) ClearDescription() *WorkoutUpdateOne {
	wuo.mutation.ClearDescription()
	return wuo
}

// SetUserID sets the "user_id" field.
func (wuo *WorkoutUpdateOne) SetUserID(pk pksuid.ID) *WorkoutUpdateOne {
	wuo.mutation.SetUserID(pk)
	return wuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wuo *WorkoutUpdateOne) SetNillableUserID(pk *pksuid.ID) *WorkoutUpdateOne {
	if pk != nil {
		wuo.SetUserID(*pk)
	}
	return wuo
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (wuo *WorkoutUpdateOne) SetUsersID(id pksuid.ID) *WorkoutUpdateOne {
	wuo.mutation.SetUsersID(id)
	return wuo
}

// SetUsers sets the "users" edge to the User entity.
func (wuo *WorkoutUpdateOne) SetUsers(u *User) *WorkoutUpdateOne {
	return wuo.SetUsersID(u.ID)
}

// AddExerciseIDs adds the "exercises" edge to the Exercise entity by IDs.
func (wuo *WorkoutUpdateOne) AddExerciseIDs(ids ...pksuid.ID) *WorkoutUpdateOne {
	wuo.mutation.AddExerciseIDs(ids...)
	return wuo
}

// AddExercises adds the "exercises" edges to the Exercise entity.
func (wuo *WorkoutUpdateOne) AddExercises(e ...*Exercise) *WorkoutUpdateOne {
	ids := make([]pksuid.ID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return wuo.AddExerciseIDs(ids...)
}

// AddWorkoutLogIDs adds the "workout_logs" edge to the WorkoutLog entity by IDs.
func (wuo *WorkoutUpdateOne) AddWorkoutLogIDs(ids ...pksuid.ID) *WorkoutUpdateOne {
	wuo.mutation.AddWorkoutLogIDs(ids...)
	return wuo
}

// AddWorkoutLogs adds the "workout_logs" edges to the WorkoutLog entity.
func (wuo *WorkoutUpdateOne) AddWorkoutLogs(w ...*WorkoutLog) *WorkoutUpdateOne {
	ids := make([]pksuid.ID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.AddWorkoutLogIDs(ids...)
}

// Mutation returns the WorkoutMutation object of the builder.
func (wuo *WorkoutUpdateOne) Mutation() *WorkoutMutation {
	return wuo.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (wuo *WorkoutUpdateOne) ClearUsers() *WorkoutUpdateOne {
	wuo.mutation.ClearUsers()
	return wuo
}

// ClearExercises clears all "exercises" edges to the Exercise entity.
func (wuo *WorkoutUpdateOne) ClearExercises() *WorkoutUpdateOne {
	wuo.mutation.ClearExercises()
	return wuo
}

// RemoveExerciseIDs removes the "exercises" edge to Exercise entities by IDs.
func (wuo *WorkoutUpdateOne) RemoveExerciseIDs(ids ...pksuid.ID) *WorkoutUpdateOne {
	wuo.mutation.RemoveExerciseIDs(ids...)
	return wuo
}

// RemoveExercises removes "exercises" edges to Exercise entities.
func (wuo *WorkoutUpdateOne) RemoveExercises(e ...*Exercise) *WorkoutUpdateOne {
	ids := make([]pksuid.ID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return wuo.RemoveExerciseIDs(ids...)
}

// ClearWorkoutLogs clears all "workout_logs" edges to the WorkoutLog entity.
func (wuo *WorkoutUpdateOne) ClearWorkoutLogs() *WorkoutUpdateOne {
	wuo.mutation.ClearWorkoutLogs()
	return wuo
}

// RemoveWorkoutLogIDs removes the "workout_logs" edge to WorkoutLog entities by IDs.
func (wuo *WorkoutUpdateOne) RemoveWorkoutLogIDs(ids ...pksuid.ID) *WorkoutUpdateOne {
	wuo.mutation.RemoveWorkoutLogIDs(ids...)
	return wuo
}

// RemoveWorkoutLogs removes "workout_logs" edges to WorkoutLog entities.
func (wuo *WorkoutUpdateOne) RemoveWorkoutLogs(w ...*WorkoutLog) *WorkoutUpdateOne {
	ids := make([]pksuid.ID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.RemoveWorkoutLogIDs(ids...)
}

// Where appends a list predicates to the WorkoutUpdate builder.
func (wuo *WorkoutUpdateOne) Where(ps ...predicate.Workout) *WorkoutUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WorkoutUpdateOne) Select(field string, fields ...string) *WorkoutUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Workout entity.
func (wuo *WorkoutUpdateOne) Save(ctx context.Context) (*Workout, error) {
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkoutUpdateOne) SaveX(ctx context.Context) *Workout {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WorkoutUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkoutUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WorkoutUpdateOne) check() error {
	if _, ok := wuo.mutation.UsersID(); wuo.mutation.UsersCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Workout.users"`)
	}
	return nil
}

func (wuo *WorkoutUpdateOne) sqlSave(ctx context.Context) (_node *Workout, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workout.Table, workout.Columns, sqlgraph.NewFieldSpec(workout.FieldID, field.TypeString))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workout.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workout.FieldID)
		for _, f := range fields {
			if !workout.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Volume(); ok {
		_spec.SetField(workout.FieldVolume, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedVolume(); ok {
		_spec.AddField(workout.FieldVolume, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.Duration(); ok {
		_spec.SetField(workout.FieldDuration, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Sets(); ok {
		_spec.SetField(workout.FieldSets, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedSets(); ok {
		_spec.AddField(workout.FieldSets, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.CreatedAt(); ok {
		_spec.SetField(workout.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.Image(); ok {
		_spec.SetField(workout.FieldImage, field.TypeJSON, value)
	}
	if wuo.mutation.ImageCleared() {
		_spec.ClearField(workout.FieldImage, field.TypeJSON)
	}
	if value, ok := wuo.mutation.Description(); ok {
		_spec.SetField(workout.FieldDescription, field.TypeString, value)
	}
	if wuo.mutation.DescriptionCleared() {
		_spec.ClearField(workout.FieldDescription, field.TypeString)
	}
	if wuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workout.UsersTable,
			Columns: []string{workout.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workout.UsersTable,
			Columns: []string{workout.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workout.ExercisesTable,
			Columns: workout.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeString),
			},
		}
		createE := &WorkoutLogCreate{config: wuo.config, mutation: newWorkoutLogMutation(wuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedExercisesIDs(); len(nodes) > 0 && !wuo.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workout.ExercisesTable,
			Columns: workout.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &WorkoutLogCreate{config: wuo.config, mutation: newWorkoutLogMutation(wuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.ExercisesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workout.ExercisesTable,
			Columns: workout.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &WorkoutLogCreate{config: wuo.config, mutation: newWorkoutLogMutation(wuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.WorkoutLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workout.WorkoutLogsTable,
			Columns: []string{workout.WorkoutLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutlog.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedWorkoutLogsIDs(); len(nodes) > 0 && !wuo.mutation.WorkoutLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workout.WorkoutLogsTable,
			Columns: []string{workout.WorkoutLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutlog.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.WorkoutLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workout.WorkoutLogsTable,
			Columns: []string{workout.WorkoutLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutlog.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Workout{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
